version: "3"
services:
  postgres:
    container_name: nestjs-react
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - /data/postgres:/data/postgres
    env_file:
    - docker.env
    networks:
    - postgres
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data/db
    networks:
      - postgres
 
networks:
  postgres:
    driver: bridge

volumes:
  redisdata:
    driver: local